<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="RSASANJEEV" ignored="0" name="AssertionTest" tests="2" failures="2" timestamp="2021-07-19T19:47:37 CDT" time="0.049" errors="0">
  <testcase name="softAssertionTestMethod" time="0.013" classname="com.testng.test.Assertion">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Failing Test1,
	Failing Test2">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Failing Test1,
Failing Test2
at com.testng.test.Assertion.softAssertionTestMethod(Assertion.java:23)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- softAssertionTestMethod -->
  <testcase name="hardAssertionTestMethod" time="0.001" classname="com.testng.test.Assertion">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.testng.test.Assertion.hardAssertionTestMethod(Assertion.java:32)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- hardAssertionTestMethod -->
</testsuite> <!-- AssertionTest -->
